/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accuracy: typeof import('./src/components/Accuracy.vue')['default']
    Calendar: typeof import('./src/components/calendar.vue')['default']
    KnoledgeGraph: typeof import('./src/components/KnoledgeGraph.vue')['default']
    KnownledgeGraph: typeof import('./src/components/KnownledgeGraph.vue')['default']
    RecentResult: typeof import('./src/components/RecentResult.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
